---
title: 'Lab 5: The Chi-Square and the Poisson'
author: "Anirudh V. S. Ruhil"
date: '2018-01-10'
output:
  html_document:
    highlight: pygments
    keep_md: yes
    mathjax: http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    theme: flatly
    toc: yes
  pdf_document:
    toc: yes
---



<div id="the-chi2-distribution" class="section level1">
<h1>The <span class="math inline">\(\chi^2\)</span> Distribution</h1>
<p>The <span class="math inline">\(\chi^2\)</span> distribution is used with multinomial data (i.e., when the categorical variable has more than two categories) to test whether observed frequency counts differ from expected frequency counts.</p>
<div id="the-goodness-of-fit-test-for-a-single-variable" class="section level2">
<h2>The Goodness-of-Fit Test for a single variable</h2>
<p><span class="math inline">\(H_0\)</span>: Proportions are all the same<br />
<span class="math inline">\(H_A\)</span>: Proportions are  all the same</p>
<p><span class="math display">\[\chi^{2} = \displaystyle\sum\limits_{i}\dfrac{\left(Observed_i - Expected_i \right)^2}{Expected_i}\]</span></p>
<p><span class="math inline">\(\chi^2\)</span> distributed with <span class="math inline">\(\left( \text{no. of categories}-1 \right)\)</span> degrees of freedom <span class="math inline">\((\textit{df})\)</span></p>
<p>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(P-value \leq \alpha\)</span>; Do not reject <span class="math inline">\(H_0\)</span> otherwise</p>
<div id="assumptions" class="section level3">
<h3>Assumptions:</h3>
<ol style="list-style-type: decimal">
<li>No category has expected frequencies <span class="math inline">\(&lt; 1\)</span></li>
<li>No more than 20% of the categories should have expected frequencies <span class="math inline">\(&lt; 5\)</span></li>
</ol>
<div id="the-steps-for-goodness-of-fit-testing" class="section level4">
<h4>The Steps for goodness-of-fit testing …</h4>
<ol style="list-style-type: decimal">
<li>Setup <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span></li>
<li>Setup <span class="math inline">\(\alpha\)</span> and the Decision-Rule</li>
<li>Calculate expected probabilities if these are not given</li>
<li>See if <span class="math inline">\(\chi^2\)</span> assumptions are violated
<ol style="list-style-type: lower-alpha">
<li>No category has expected frequencies <span class="math inline">\(&lt; 1\)</span></li>
<li>No more than 20% of the categories should have expected frequencies <span class="math inline">\(&lt; 5\)</span></li>
</ol></li>
<li>If either assumption is violated then you will need to collapse the categories and start again from Step (3)</li>
<li>Conduct the test</li>
<li>Adjust for having estimated <span class="math inline">\(P(X)\)</span> from the data by using <span class="math inline">\(df= n - 1 - 1 = n-2\)</span></li>
<li>State your conclusion (in words)</li>
</ol>
</div>
</div>
</div>
</div>
<div id="some-practice" class="section level1">
<h1>Some Practice</h1>
<div id="four-health-campaigns" class="section level2">
<h2>Four Health Campaigns</h2>
<p><span class="math inline">\(H_0:\)</span> Proportions of the sample recalling any commercial are the same<br />
<span class="math inline">\(H_A:\)</span> Proportions of the sample recalling any commercial are NOT the same</p>
<p>Set <span class="math inline">\(\alpha\)</span>; I choose 0.05</p>
<p>Decision Rule: Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p-value \leq \alpha\)</span>; do not reject otherwise.</p>
<pre class="r"><code>observed = c(85, 95, 50, 70)
expected = c(75, 75, 75, 75)
tab.00 = cbind(observed, expected); tab.00 # just to see obs vs. exp</code></pre>
<pre><code>##      observed expected
## [1,]       85       75
## [2,]       95       75
## [3,]       50       75
## [4,]       70       75</code></pre>
<pre class="r"><code>chisq.test(observed, p=c(0.25, 0.25, 0.25, 0.25))</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  observed
## X-squared = 15.333, df = 3, p-value = 0.001553</code></pre>
<p>The p-value is 0.001553 so we can easily reject <span class="math inline">\(H_0\)</span>; the data suggest that recall rates differ across the four health campaigns.</p>
</div>
<div id="mms" class="section level2">
<h2>M&amp;Ms</h2>
<p>Here we are given the proportion of the colors the company would like in each bag. We have the observed frequencies as well.</p>
<p><span class="math inline">\(H_0:\)</span> The proportion of colors follows the specified distribution<br />
<span class="math inline">\(H_A:\)</span> The proportion of colors DOES NOT follow the specified distribution</p>
<p>Set <span class="math inline">\(\alpha\)</span>; I choose 0.05</p>
<p>Decision Rule: Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p-value \leq \alpha\)</span>; do not reject otherwise.</p>
<pre class="r"><code>expected = c(0.3, 0.2, 0.2, 0.1, 0.1, 0.1)
observed = c(177, 135, 79, 41, 36, 38)
chisq.test(observed, p=expected)</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  observed
## X-squared = 29.514, df = 5, p-value = 1.838e-05</code></pre>
<p>Given the low p-value we reject <span class="math inline">\(H_0\)</span>; the data suggest that the color distribution is NOT what the company would like to see.</p>
</div>
<div id="number-of-boys" class="section level2">
<h2>Number of Boys</h2>
<p>Is the sex of consecutive children independent in humans? Does having one boy change the probability of the next child also being a boy? We looked at this with decision trees in Chapter 5. Here we use data compiled by Rodgers and Doughty (2011) to test for independence – whether the sex of the first child influences (or not) the sex of the second child.</p>
<pre class="r"><code>families = read.csv(url(&quot;http://whitlockschluter.zoology.ubc.ca/wp-content/data/chapter08/chap08e5NumberOfBoys.csv&quot;))
head(families)</code></pre>
<pre><code>##   numberOfBoys
## 1            0
## 2            0
## 3            0
## 4            0
## 5            0
## 6            0</code></pre>
<pre class="r"><code>tab.2 = table(families); tab.2</code></pre>
<pre><code>## families
##    0    1    2 
##  530 1332  582</code></pre>
<p><span class="math inline">\(H_0: \text{ No. of Boys in two-child families follows the binomial distribution}\)</span></p>
<p><span class="math inline">\(H_A: \text{ No. of Boys in two-child families does not follow the binomial distribution}\)</span></p>
<p>We need to start by calculating the probability of a boy being born in any given randomly selected birth. Given the sample but no population information, we’ll have to calculate this probability from the sample. Total number of boys = 2496. Total sample size is 4888 children. So the probability of a boy is:</p>
<pre class="r"><code>p.boy = 2496/4888; p.boy</code></pre>
<pre><code>## [1] 0.5106383</code></pre>
<p>If this is the base probability of seeing a boy in any randomly chosen birth, how often would we see 0 boys, 1 boy, 2 boys? The binomial distribution can tell us:</p>
<pre class="r"><code>x = seq(0, 2, by=1) # create a sequence that goes from 0 boys to 1 boy to 2 boys
y = dbinom(x, 2, p = p.boy) # probability of seeing no boys, 1 boy, 2 boys
y </code></pre>
<pre><code>## [1] 0.2394749 0.4997737 0.2607515</code></pre>
<pre class="r"><code>sum(y) # Making sure the probabilities sum to 1</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>chisq.test(tab.2, p=y) # the actual chi-square test</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  tab.2
## X-squared = 20.021, df = 2, p-value = 4.492e-05</code></pre>
<p>The p-value is small so we would reject <span class="math inline">\(H_0\)</span> but we have to adjust the degrees of freedom. Why? Because we used up one additional degree of freedom by using the sample to calculate <code>p.boy</code>. The correct p-value is thus:</p>
<pre class="r"><code>1 - pchisq(20.021, df=1)</code></pre>
<pre><code>## [1] 7.659634e-06</code></pre>
<p>Now we can safely reject <span class="math inline">\(H_0\)</span>; the data suggest that the number of boys in two-child families does not follow the binomial distribution.</p>
<p>What does this mean? This means that somehow the probability of having a son or daughter appears to vary across families, maybe having a boy does influence the chance of having another boy or a girl, or something else is going on here that violates one of the the assumptions of the binomial distribution – that what happens in one trial has no bearing on what happens in the next trial.</p>
</div>
</div>
<div id="the-poisson-distribution" class="section level1">
<h1>The Poisson Distribution</h1>
<p>The Poisson distribution describes the number of successes that will occur in space or time if the number of successes are independent across consecutive space or time and occur with equal probability in each space or time. It is a useful distribution if our goal is to test whether or not events occur randomly in space and/or time because if they do, then the Poisson distribution would characterize these events quite well.</p>
<p><span class="math display">\[P(X) = \dfrac{e^{-\mu} \mu^{X}}{X!}; \text{where } X=0,1,2,3,\ldots, n; \text{and Mean }= \text{Variance } = \mu\]</span></p>
<p>where <span class="math inline">\(X=\)</span> the number of events in a given time interval or space; <span class="math inline">\(\mu=\)</span> the mean number of events per time interval or space; and <span class="math inline">\(P(X)=\)</span> the probability of observing exactly <span class="math inline">\(X\)</span> events in a given interval.</p>
<p>For example: Hospital births occur on average at 1.8 births per hour. What is <span class="math inline">\(P(X=4)\)</span>?</p>
<p><span class="math display">\[P(X=4) = \dfrac{e^{-1.8}(1.8)^4}{4!} = 0.0723\]</span></p>
<div id="key-assumptions" class="section level2">
<h2>Key Assumptions</h2>
<ol style="list-style-type: decimal">
<li>The probability of observing a single event over a small time interval (or space) is approximately proportional to the size of that time interval (or space) .</li>
<li>The probability of two events occurring in the same narrow time interval (or space) is negligible.</li>
<li>The probability of an event within a certain time interval (or space) does not change across different time intervals (or space) .</li>
<li>The probability of an event in one time interval (or space) is independent of the probability of an event in any other non-overlapping time interval (or space).</li>
</ol>
<p>Note:</p>
<ul>
<li>Clumping occurs when the mean is <em>less than</em> the variance</li>
<li>Dispersion occurs when the mean is <em>greater than</em> the variance</li>
</ul>
</div>
<div id="the-steps" class="section level2">
<h2>- The Steps …</h2>
<ol style="list-style-type: decimal">
<li>Setup <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span></li>
<li>Setup <span class="math inline">\(\alpha\)</span> and the Decision-Rule</li>
<li>Calculate the mean <span class="math inline">\((\mu)\)</span></li>
<li>Use <span class="math inline">\(\mu\)</span> to calculate expected frequencies for counts = <span class="math inline">\(0, 1, 2, 3, \cdots\)</span></li>
<li>See if <span class="math inline">\(\chi^2\)</span> assumptions are violated
<ol style="list-style-type: lower-alpha">
<li>No category has expected frequencies <span class="math inline">\(&lt; 1\)</span></li>
<li>No more than 20% of the categories should have expected frequencies <span class="math inline">\(&lt; 5\)</span></li>
</ol></li>
<li>If either assumption is violated then you will need to collapse the categories and start again from Step (3)</li>
<li>Conduct the test.</li>
<li>Adjust for having estimated <span class="math inline">\(\mu\)</span> from the data by using <span class="math inline">\(df= n - 1 - 1 = n-2\)</span></li>
<li>State your conclusion (in words)</li>
</ol>
<div id="an-example-mass-extinctions-in-the-fossil-record" class="section level3">
<h3>An Example: Mass Extinctions in the Fossil Record</h3>
<p>Do extinctions occur randomly through the long fossil record of Earth’s history or are there periods in which the extinction rates are unusually high (“mass extinctions”) compared with background rates? We can test this hypothesis via data on the number of recorded extinctions of marine invertebrate families in 76 time intervals. If mass extinctions are indeed random in time then the distribution should follow the Poisson, with any departures from the Poisson suggesting that something must have been going on.</p>
<p><span class="math display">\[H_0: \text{Number of extinctions follow the Poisson distribution }\]</span><br />
<span class="math display">\[H_A: \text{Number of extinctions DO NOT follow the Poisson distribution }\]</span></p>
<pre class="r"><code>extinct = read.csv(url(&quot;http://whitlockschluter.zoology.ubc.ca/wp-content/data/chapter08/chap08e6MassExtinctions.csv&quot;))
head(extinct)</code></pre>
<pre><code>##   numberOfExtinctions
## 1                   1
## 2                   1
## 3                   1
## 4                   1
## 5                   1
## 6                   1</code></pre>
<pre class="r"><code>names(extinct)</code></pre>
<pre><code>## [1] &quot;numberOfExtinctions&quot;</code></pre>
<pre class="r"><code>tab.A = table(extinct); tab.A # Note missing &quot;0&quot; here versus the text</code></pre>
<pre><code>## extinct
##  1  2  3  4  5  6  7  8  9 10 11 14 16 20 
## 13 15 16  7 10  4  2  1  2  1  1  1  2  1</code></pre>
<pre class="r"><code>mean(extinct$numberOfExtinctions)</code></pre>
<pre><code>## [1] 4.210526</code></pre>
<pre class="r"><code>plot(tab.A, ylim=c(0,20), xaxt=&quot;n&quot;, type=&quot;h&quot;, xlab=&quot;Number of Mass Extinctions&quot;, ylab=&quot;Frequency&quot;, col=&quot;firebrick&quot;, cex.axis=0.8)
at = seq(from = 0, to = 20, by = 1)
axis(side = 1, at = at, cex.axis=0.8)</code></pre>
<p><img src="/teaching/pbio/Lab05_files/figure-html/extinctions1-1.png" width="672" /></p>
<p>This is all good but we need to estimate the population mean <span class="math inline">\((\lambda)\)</span> of mass extinctions. Since we only have these particular sample data to go by, that is precisely what we will use to get <span class="math inline">\(\hat{\lambda}\)</span> and treat this <span class="math inline">\(\hat{\lambda} = \lambda\)</span>.</p>
<p>As it turns out, <span class="math inline">\(\lambda=\)</span> <code>4.2105263</code></p>
<p>Given <span class="math inline">\(\lambda\)</span>, we can now calculate the probability of seeing no mass extinctions, 1 mass extinctions, 2 mass extinctions, and so on if indeed mass extinctions follow a Poisson distribution with a mean of 4.210526.</p>
<pre class="r"><code>x = seq(0, 20, by=1)
x.d = dpois(x, lambda=4.210526); x.d # probs of 0, 1, 2, ... mass extinctions</code></pre>
<pre><code>##  [1] 1.483856e-02 6.247815e-02 1.315329e-01 1.846076e-01 1.943238e-01
##  [6] 1.636411e-01 1.148358e-01 6.907418e-02 3.635483e-02 1.700811e-02
## [11] 7.161307e-03 2.741170e-03 9.618139e-04 3.115187e-04 9.368982e-05
## [16] 2.629889e-05 6.920761e-06 1.714120e-06 4.009638e-07 8.885623e-08
## [21] 1.870657e-08</code></pre>
<pre class="r"><code>sum(x.d) # making sure the probabilities sum to 1</code></pre>
<pre><code>## [1] 1</code></pre>
<p>Thus, in a random sample of 76 successive time intervals we would expect to see</p>
<pre class="r"><code>x.d*76 </code></pre>
<pre><code>##  [1] 1.127731e+00 4.748339e+00 9.996503e+00 1.403018e+01 1.476861e+01
##  [6] 1.243672e+01 8.727523e+00 5.249638e+00 2.762967e+00 1.292616e+00
## [11] 5.442593e-01 2.083289e-01 7.309786e-02 2.367542e-02 7.120426e-03
## [16] 1.998716e-03 5.259778e-04 1.302731e-04 3.047325e-05 6.753074e-06
## [21] 1.421700e-06</code></pre>
<p>proportion of intervals with 0, 1, 2, 3, … mass extinctions.</p>
<p>Let us calculate the expected frequencies:</p>
<pre class="r"><code>expected = dpois(x, 4.210526) * 76
expected</code></pre>
<pre><code>##  [1] 1.127731e+00 4.748339e+00 9.996503e+00 1.403018e+01 1.476861e+01
##  [6] 1.243672e+01 8.727523e+00 5.249638e+00 2.762967e+00 1.292616e+00
## [11] 5.442593e-01 2.083289e-01 7.309786e-02 2.367542e-02 7.120426e-03
## [16] 1.998716e-03 5.259778e-04 1.302731e-04 3.047325e-05 6.753074e-06
## [21] 1.421700e-06</code></pre>
<pre class="r"><code>round(expected, digits=2)  # rounding to two decimal places</code></pre>
<pre><code>##  [1]  1.13  4.75 10.00 14.03 14.77 12.44  8.73  5.25  2.76  1.29  0.54
## [12]  0.21  0.07  0.02  0.01  0.00  0.00  0.00  0.00  0.00  0.00</code></pre>
<p>Because the observed number of extinctions start thinning at the upper end of the distribution, violating the assumptions of <span class="math inline">\(\chi^2\)</span>, we need to collapse the first two (0 and 1) and the top end of the distribution into an omnibus category that we can call “10 or more”. We do so below:</p>
<pre class="r"><code>new.ME = c(&quot;0 or 1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4&quot;, &quot;5&quot;, &quot;6&quot;, &quot;7&quot;, &quot;8 or more&quot;); new.ME</code></pre>
<pre><code>## [1] &quot;0 or 1&quot;    &quot;2&quot;         &quot;3&quot;         &quot;4&quot;         &quot;5&quot;         &quot;6&quot;        
## [7] &quot;7&quot;         &quot;8 or more&quot;</code></pre>
<pre class="r"><code>new.counts = c(tab.A[1], tab.A[2:7], sum(tab.A[8:14]) ) # collapsing
new.counts</code></pre>
<pre><code>##  1  2  3  4  5  6  7    
## 13 15 16  7 10  4  2  9</code></pre>
<pre class="r"><code>names(new.counts) = new.ME # naming the new categories
new.counts # now seeing them with the labels for each category</code></pre>
<pre><code>##    0 or 1         2         3         4         5         6         7 
##        13        15        16         7        10         4         2 
## 8 or more 
##         9</code></pre>
<pre class="r"><code>sum(new.counts) # To verify we didn&#39;t mess up somewhere and we still have 76 extinctions</code></pre>
<pre><code>## [1] 76</code></pre>
<p>We aren’t done yet. Since we have rearranged the grouping we will need to recalculate the expected frequencies.</p>
<pre class="r"><code>x = seq(0 , 20, by = 1)
new.probs = dpois(x, 4.210526); new.probs</code></pre>
<pre><code>##  [1] 1.483856e-02 6.247815e-02 1.315329e-01 1.846076e-01 1.943238e-01
##  [6] 1.636411e-01 1.148358e-01 6.907418e-02 3.635483e-02 1.700811e-02
## [11] 7.161307e-03 2.741170e-03 9.618139e-04 3.115187e-04 9.368982e-05
## [16] 2.629889e-05 6.920761e-06 1.714120e-06 4.009638e-07 8.885623e-08
## [21] 1.870657e-08</code></pre>
<pre class="r"><code>prob.0or1 = sum(new.probs[1:2]); prob.0or1</code></pre>
<pre><code>## [1] 0.07731671</code></pre>
<pre class="r"><code>prob.2to7 = new.probs[3:8]; prob.2to7</code></pre>
<pre><code>## [1] 0.13153293 0.18460761 0.19432379 0.16364107 0.11483583 0.06907418</code></pre>
<pre class="r"><code>prob.8plus = 1 - sum(prob.0or1, prob.2to7); prob.8plus</code></pre>
<pre><code>## [1] 0.06466788</code></pre>
<pre class="r"><code>probs = c(prob.0or1, prob.2to7, prob.8plus); probs</code></pre>
<pre><code>## [1] 0.07731671 0.13153293 0.18460761 0.19432379 0.16364107 0.11483583
## [7] 0.06907418 0.06466788</code></pre>
<pre class="r"><code>sum(probs)</code></pre>
<pre><code>## [1] 1</code></pre>
<p>Now we conduct the <span class="math inline">\(\chi^2\)</span> test:</p>
<pre class="r"><code>xsq = chisq.test(new.counts, p=probs, correct=FALSE); xsq</code></pre>
<pre><code>## Warning in chisq.test(new.counts, p = probs, correct = FALSE): Chi-squared
## approximation may be incorrect</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  new.counts
## X-squared = 23.95, df = 7, p-value = 0.001163</code></pre>
<pre class="r"><code>xsq$observed # Observed frequencies used in the test</code></pre>
<pre><code>##    0 or 1         2         3         4         5         6         7 
##        13        15        16         7        10         4         2 
## 8 or more 
##         9</code></pre>
<pre class="r"><code>xsq$expected # Expected frequencies used in the test</code></pre>
<pre><code>##    0 or 1         2         3         4         5         6         7 
##  5.876070  9.996503 14.030178 14.768608 12.436721  8.727523  5.249638 
## 8 or more 
##  4.914759</code></pre>
<p>You get a warning <code>Warning message: In chisq.test(new.counts, p = probs, correct = FALSE):</code> because one of the expected frequencies is less than 5 but we should be okay here since we need 20% of the cells to have expected frequencies <span class="math inline">\(&lt; 5\)</span> or at least one cell with expected frequency <span class="math inline">\(&lt; 1\)</span> before the <span class="math inline">\(\chi^2\)</span> assumptions are unmet.</p>
<p>The <span class="math inline">\(\chi^2\)</span> value is 23.95 with a <span class="math inline">\(p-Value = 0.001163\)</span>. This is again incorrect because of the extra degree of freedom used up when we were forced to calculate the mean of the Poisson process from the sample. The correct <span class="math inline">\(p-value\)</span> can be calculated with one less degree of freedom as:</p>
<pre class="r"><code>1 - pchisq(23.95, df=6)</code></pre>
<pre><code>## [1] 0.0005334336</code></pre>
<p>Given the p-value we can easily reject H0; the data provide sufficient evidence to conclude that mass extinctions in the fossil record DO NOT fit a Poisson distribution.</p>
</div>
</div>
<div id="practice-problems" class="section level2">
<h2>Practice Problems</h2>
<div id="world-cup-goals-problem-4" class="section level3">
<h3>World Cup Goals (Problem 4)</h3>
<p>How much do skill differences determine the outcome of soccer matches in the World Cup? If the probability of a goal is the same for all teams and matches, and if each goal is independent of another, then the distribution of goals per game should approximate the Poisson distribution. The data at hand are given below:</p>
<pre class="r"><code>goals = read.csv(&quot;http://whitlockschluter.zoology.ubc.ca/wp-content/data/chapter08/chap08q05WorldCup.csv&quot;)</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Plot the frequency distribution of goals per team.</li>
</ol>
<pre class="r"><code>tab.goals = table(goals$score); tab.goals</code></pre>
<pre><code>## 
##  0  1  2  3  4  5  8 
## 37 47 27 13  2  1  1</code></pre>
<pre class="r"><code>plot(tab.goals, ylim=c(0,50),
     type = &quot;h&quot;, lwd=3, col=&quot;tomato4&quot;, 
     ylab = &quot;Frequency&quot;, 
     xlab=&quot;Score&quot;,
     main = &quot;Frequency Distribution of Scores&quot;,
     sub = &quot;(in World Cup matches)&quot;,
     cex.main=0.99) </code></pre>
<p><img src="/teaching/pbio/Lab05_files/figure-html/goalsplot-1.png" width="672" /></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the mean number of goals?</li>
</ol>
<pre class="r"><code>mean.goals = mean(goals$score); mean.goals</code></pre>
<pre><code>## [1] 1.257812</code></pre>
<p>The mean number of goals scored is <code>mean.goals</code>.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Test whether the Poisson distribution characterizes the distribution of goals per game.</li>
</ol>
<p>Note: If we collapse games with 4, 5, and 8 goals, respectively, into an omnibus “4 or more” category we should be able to get around the problem of “thin cells” at the top of the distribution. So the new categories will be:</p>
<pre class="r"><code>new.cats = c(tab.goals[1:4], sum(tab.goals[5:7]))
sum(new.cats) # to see if the sample size is correct</code></pre>
<pre><code>## [1] 128</code></pre>
<pre class="r"><code>names(new.cats) = c(&quot;0&quot;, &quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4 or more&quot;)
new.cats</code></pre>
<pre><code>##         0         1         2         3 4 or more 
##        37        47        27        13         4</code></pre>
<p>Now we are fine since exactly 20% of our cells have expected frequencies <span class="math inline">\(&lt; 5\)</span>.</p>
<p><span class="math inline">\(H_0:\)</span> Goals per game follow the Poisson distribution<br />
<span class="math inline">\(H_A:\)</span> Goals per game DO NOT follow the Poisson distribution</p>
<p><span class="math inline">\(\alpha=0.05\)</span></p>
<p>Reject <span class="math inline">\(H_0\)</span> if the p-value is <span class="math inline">\(\leq \alpha\)</span>; do not reject <span class="math inline">\(H_0\)</span> otherwise</p>
<pre class="r"><code>x = seq(0, 5, by=1)
probs = dpois(x, lambda=mean.goals); probs</code></pre>
<pre><code>## [1] 0.284275199 0.357564899 0.224874799 0.094283445 0.029647724 0.007458256</code></pre>
<pre class="r"><code>sum(probs) # checking the sum of probabilities</code></pre>
<pre><code>## [1] 0.9981043</code></pre>
<pre class="r"><code>new.probs = c(probs[1:4], 1 - sum(probs[1:4])) # adjusting probabilities to sum to 1
new.probs # checking the new probabilities</code></pre>
<pre><code>## [1] 0.28427520 0.35756490 0.22487480 0.09428344 0.03900166</code></pre>
<pre class="r"><code>expected = new.probs * 128
expected #expected number of 0, 1, 2, ... goals </code></pre>
<pre><code>## [1] 36.387225 45.768307 28.783974 12.068281  4.992212</code></pre>
<pre class="r"><code>xsq = chisq.test(new.cats, p=new.probs); xsq</code></pre>
<pre><code>## Warning in chisq.test(new.cats, p = new.probs): Chi-squared approximation
## may be incorrect</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  new.cats
## X-squared = 0.42317, df = 4, p-value = 0.9805</code></pre>
<pre class="r"><code>1 - pchisq(0.42317, df=3)</code></pre>
<pre><code>## [1] 0.9354156</code></pre>
<p>The p-value is quite high so we fail to reject <span class="math inline">\(H_0\)</span>; the data suggest that the distribution of goals in the World Cup follows the Poisson distribution.</p>
<p>We can check our observed versus expected frequencies (if we wanted to be doubly sure):</p>
<pre class="r"><code>xsq$observed</code></pre>
<pre><code>##         0         1         2         3 4 or more 
##        37        47        27        13         4</code></pre>
<pre class="r"><code>xsq$expected</code></pre>
<pre><code>##         0         1         2         3 4 or more 
## 36.387225 45.768307 28.783974 12.068281  4.992212</code></pre>
<p>It is quite obvious that there is marginal drift between our observed frequencies and what we would have expected to see if goals were distributed Poisson.</p>
</div>
</div>
</div>
<div id="practice-problems-1" class="section level1">
<h1>Practice Problems</h1>
<div id="falling-cats" class="section level3">
<h3>Falling Cats</h3>
<p>A study of the Feline High-Rise Syndrome (FHRS) included data on the number of cats that fell in a given month. Can we infer that the rate of cats falling varies between months of the year?</p>
<pre class="r"><code>cats = read.csv(&quot;http://whitlockschluter.zoology.ubc.ca/wp-content/data/chapter08/chap08q21FallingCatsByMonth.csv&quot;)
tab.cats = table(cats$month); tab.cats</code></pre>
<pre><code>## 
##     April    August  December  February   January      July      June 
##        10        13         5         6         4        19        14 
##     March       May  November   October September 
##         8         9         7        12        12</code></pre>
<p>The months are not ordered correctly. Let us fix this first:</p>
<pre class="r"><code>cats$month = ordered(cats$month, levels = c(&quot;January&quot;, &quot;February&quot;, &quot;March&quot;, &quot;April&quot;, &quot;May&quot;, &quot;June&quot;, &quot;July&quot;, &quot;August&quot;, &quot;September&quot;, &quot;October&quot;, &quot;November&quot;, &quot;December&quot;))

tab.cats = table(cats$month); tab.cats</code></pre>
<pre><code>## 
##   January  February     March     April       May      June      July 
##         4         6         8        10         9        14        19 
##    August September   October  November  December 
##        13        12        12         7         5</code></pre>
<ol style="list-style-type: lower-alpha">
<li><p>Plot the distribution of FHRS in these data.</p></li>
<li><p>Test whether FHRS rate varies across the months of the year.</p></li>
</ol>
</div>
<div id="snapdragons" class="section level3">
<h3>Snapdragons</h3>
<p>In snapdragons, variation in flower colors is determined by a single gene. <em>RR</em> individuals are red, <em>Rr</em> (heterozygous) are pink, and <em>rr</em> are white. In a cross between heterozygous individual, the expected ratio of red-flowered:pink-flowered:white-flowered offspring is 1:2:1.</p>
<ol style="list-style-type: lower-alpha">
<li><p>The results of such a cross were 10 red, 21 pink, and 9 white offspring. Do these results differ significantly from that expected by the 1:2:1 ratio?</p></li>
<li><p>In another experiment, you count 100 times as many flowers and end up with 1000 red, 2100 pink, and 900 white. Do these results differ significantly from that expected by the 1:2:1 ratio?</p></li>
<li><p>Do the proportions observed in (a) and (b) differ? Did the results of your hypothesis test differ? Why or why not?</p></li>
</ol>
</div>
<div id="shark-attacks" class="section level3">
<h3>Shark Attacks</h3>
<p>In recent years shark attacks have drawn attention every summer. The data below reflect the number of shark attacks per year for the 2005 through 2014 years:</p>
<pre class="r"><code>attacks = c(58, 59, 70, 55, 68, 82, 79, 83, 76, 72)
year = c(seq(2005, 2014, by=1))
sharks = cbind.data.frame(year, attacks)</code></pre>
<ol style="list-style-type: lower-alpha">
<li><p>Plot the distribution of shark attacks.</p></li>
<li><p>If shark attacks occur randomly and independently across years, what distribution would shark attacks follow?</p></li>
</ol>
</div>
<div id="hurricanes" class="section level3">
<h3>Hurricanes</h3>
<p>The Saffir-Simpson scale rates hurricane on a five-point rating system, with Category 5 being the worst. The data given here <a href="http://whitlockschluter.zoology.ubc.ca/wp-content/data/chapter08/chap08q19Hurricanes.csv" class="uri">http://whitlockschluter.zoology.ubc.ca/wp-content/data/chapter08/chap08q19Hurricanes.csv</a> reflect the number of Cat 3 hurricanes over a one-hundred year period in the U.S.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Based on these data, what is the mean number of severe hurricanes to hit the U.S. per year?</p></li>
<li><p>What model would describe the distribution of hurricanes per year if hurricanes hit independently of each other and the probability of a hurricane were the same in every year?</p></li>
<li><p>Test the fit of the model you identified in (b) to these data. Be sure to specify the hypotheses, the <span class="math inline">\(\alpha\)</span>, and the decision rule. Once you conduct the test, state your decision and hence your conclusion (in words).</p></li>
</ol>
</div>
</div>
