---
title: "Lab 3"
author: "Ani Ruhil"
date: "January 25, 2016"
output:
  html_document:
    highlight: tango
    theme: readable
    toc: yes
  fontsize: 10
  word_document:
    highlight: tango
    toc: yes
---



<div id="practice-problem-1" class="section level1">
<h1>Practice Problem 1</h1>
<p>Systolic blood pressure was measured (in units of mm Hg) during preventative health examinations on people in Dallas, Texas. Here are the measurements for some of these patients:</p>
<pre class="r"><code>y = c(112, 128, 108, 129, 125, 153, 155, 132, 137)</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Calculate the mean and the standard deviation for these data.</li>
</ol>
<pre class="r"><code>mean.y = mean(y)
sd.y =sd(y)
mean.y; sd.y</code></pre>
<pre><code>## [1] 131</code></pre>
<pre><code>## [1] 15.95306</code></pre>
<p>The mean is 131 mm Hg and the standard deviation is 15.93 mm Hg.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the sample size?</li>
</ol>
<pre class="r"><code>n = length(y)
n</code></pre>
<pre><code>## [1] 9</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Calculate the standard error of the mean.</li>
</ol>
<pre class="r"><code>se.y = sd.y / sqrt(n)
se.y</code></pre>
<pre><code>## [1] 5.317685</code></pre>
<p>The standard error of the mean is 5.31</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Using the 2SE rule of thumb, calculate an approximate 95% confidence interval for the mean. List the lower and upper limits.</li>
</ol>
<pre class="r"><code>lower.CI.limit = mean.y - (2 * se.y)
upper.CI.limit = mean.y + (2 * se.y)
lower.CI.limit; upper.CI.limit</code></pre>
<pre><code>## [1] 120.3646</code></pre>
<pre><code>## [1] 141.6354</code></pre>
<p>The lower and upper limits of the confidence interval are 120.36 mm Hg and 141.63 mm Hg.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>How would we interpret the 95% confidence interval?</li>
</ol>
<p>We can be about 95% certain that the population mean of systolic blood pressure lies in the range of values given by 120.36 mm Hg and 141.63 mm Hg.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Draw a strip-chart with the mean and the standard errors overlaid on the data.</li>
</ol>
<pre class="r"><code>par(bty = &quot;l&quot;) # Just draw x-axis and y-axis; no box around the plot

stripchart(y, vertical = TRUE, method = &quot;jitter&quot;, jitter = 0.01, pch = 16, ylab = &quot;Blood Pressure (in mm Hg)&quot;, col = &quot;cadetblue1&quot;, cex = 1, las = 1, ylim = c(0, max(y)))

points(mean.y, pch = 16, cex = 1.2)

arrows( c(1), mean.y - se.y, c(1), mean.y + se.y,   angle = 90, code = 3, length = 0.1)</code></pre>
<p><img src="/teaching/pbio/Lab03_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="practice-problem-7" class="section level1">
<h1>Practice Problem 7</h1>
<p>Niderkorn’s (1872) measurements on 114 human corpses provided the first quantitative study on the development of rigor mortis. These data, given below, reflect the number of hours it took a body to achieve rigor mortis after death. Note the data have been rounded to the nearest hour (hence there are no decimal places).</p>
<pre class="r"><code>rmortis = read.csv(&quot;http://whitlockschluter.zoology.ubc.ca/wp-content/data/chapter03/chap03q09Rigormortis.csv&quot;)</code></pre>
<ol style="list-style-type: lower-alpha">
<li>What is the average time to rigor mortis for these data?</li>
</ol>
<pre class="r"><code>mean.hours = mean(rmortis$hours)
mean.hours</code></pre>
<pre><code>## [1] 5.684211</code></pre>
<p>The average time to rigor mortis is 5.68 hours.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the standard deviation?</li>
</ol>
<pre class="r"><code>sd.hours = sd(rmortis$hours)
sd.hours</code></pre>
<pre><code>## [1] 2.362374</code></pre>
<p>The standard deviation is 2.36 hours.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Calculate and interpret the standard error for the mean of these data.</li>
</ol>
<pre class="r"><code>n.hours = length(rmortis$hours)
n.hours</code></pre>
<pre><code>## [1] 114</code></pre>
<pre class="r"><code>se.hours = sd.hours / sqrt(n.hours)
se.hours</code></pre>
<pre><code>## [1] 0.2212566</code></pre>
<p>The standard error is 0.22 hours, and this can be interpreted as the average difference we might expect, between our sample mean and the population, in a random sample of 114 cadavers.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>What is the approximate 95% confidence interval for the sample mean you estimated earlier? How would we interpret the lower and upper limits of this interval?</li>
</ol>
<pre class="r"><code>lower.CI = mean.hours - (2 * se.hours)
upper.CI = mean.hours + (2 * se.hours)
lower.CI; upper.CI</code></pre>
<pre><code>## [1] 5.241697</code></pre>
<pre><code>## [1] 6.126724</code></pre>
<p>The approximate 95% interval is 5.24 and 6.12 hours. The interpretation would be that we can be about 95% certain that for the population at large the average time to rigor mortis falls between 5.24 and 6.12 hours.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Draw a strip-chart with the mean and the standard errors overlaid on the data.</li>
</ol>
<pre class="r"><code>par(bty = &quot;l&quot;) # Just draw x-axis and y-axis; no box around the plot

stripchart(rmortis$hours, vertical = TRUE, method = &quot;jitter&quot;, jitter = 0.01, pch = 16, ylab = &quot;Time to Rigor Mortis (in hours)&quot;, col = &quot;cadetblue1&quot;, cex = 1, las = 1, ylim = c(0, max(rmortis$hours)))

points(mean.hours, pch = 16, cex = 1.2)

arrows( c(1), mean.hours - se.hours, c(1), mean.hours + se.hours,   angle = 90, code = 3, length = 0.1)</code></pre>
<p><img src="/teaching/pbio/Lab03_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="your-turn" class="section level1">
<h1>Your Turn …</h1>
<p>The data below document the flash duration, in milliseconds, of a sample of 35 male fireflies of the species <em>Photinus Ignitus</em>.</p>
<pre class="r"><code>flash = read.csv(&quot;http://whitlockschluter.zoology.ubc.ca/wp-content/data/chapter04/chap04q07FireflyFlash.csv&quot;)


mean = mean(flash$flash)
sd = sd(flash$flash)
n = 70
se = sd / sqrt(n)

ci.low = mean - (2*se)
ci.high = mean + (2*se)</code></pre>
<ol style="list-style-type: lower-alpha">
<li><p>Calculate the sample mean and the sample standard deviation.</p></li>
<li><p>Calculate the standard error and interpret it.</p></li>
<li><p>Calculate the approximate 95% confidence interval for the mean flash duration.</p></li>
<li><p>Interpret the confidence interval you calculated above.</p></li>
<li><p>Draw a strip chart with the mean and standard error superimposed on the data.</p></li>
<li><p>If you had twice the sample size, say for 70 male fireflies, would your estimated standard error be smaller or larger? What would be the consequence for the approximate 95% confidence interval – would it be wider or narrower than what you calculated above? Show your conclusions by:</p></li>
</ol>
<ul>
<li>using a sample size of 70 to calculate the new standard error</li>
<li>then using the new standard error to calculate the approximate 95% confidence interval for mean flash duration of male fireflies</li>
</ul>
</div>
